name: List S3 Objects

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  list-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: <your-AWS-region>

      - name: List objects in S3 bucket
        run: |
          aws s3 ls s3://<bucket-name>/
