name: Echo .env File

on:
  push:
    branches:
      - main

jobs:
  echo-env-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Echo .env file
        run: cat $GITHUB_WORKSPACE/.env
