name: List S3 Objects

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  list-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install AWS CLI
        run: |
          pip install awscli --upgrade --user

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region <your-AWS-region>

      - name: List objects in S3 bucket
        run: |
          aws s3 ls s3://<bucket-name>/
