name: Create Folder in S3 Bucket

on:
  push:
    branches:
      - main  # adjust branch name as needed

jobs:
  create-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          pip install awscli --upgrade --user
          pip install python-dotenv

      - name: Load environment variables
        run: |
          source .env

      - name: Set up AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region eu-west-1

      - name: Create folder in S3 bucket
        run: |
          aws s3api put-object --bucket aws-de-demo-bkt --key $F/
