name: Extract script_path

on:
  push:
    branches:
      - main

jobs:
  extract-script-path:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract script_path
        run: |
          script_path=$(grep '^script_path=' .env | awk -F '=' '{print $2}')
          echo "The value of script_path is $script_path"
          ls
